{% set name = "napari-bigfish" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f241f3ef6c86224f81b60f981f5308adbfb002a657e3e4502d631c9a160edcd2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - big-fish
    - magicgui
    - napari
    - numpy
    - pyperclip
    - python >=3.8
    - qtpy
    - scikit-image

test:
  imports:
    - napari_bigfish
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MontpellierRessourcesImagerie/napari-bigfish
  summary: |
    A napari-plugin providing an alternative GUI for Big-FISH.
    Big-FISH is a python package for the analysis of smFISH images.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
